services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-api
    working_dir: /app
    ports:
      - "8080:80"
    volumes:
      - ./app/api:/app
    environment:
      SERVER_NAME: :80
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}?charset=utf8mb4
    depends_on:
      - db

  client:
    image: node:20-alpine
    container_name: ${PROJECT_NAME}-client
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./app/client:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    command: sh -c "npm install && npm run dev"

  db:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}-db
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}-pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      # Cette ligne permet d'entrer directement sans login
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: {}
